# Generated by Django 5.2.15 on 2026-06-30 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('slug', models.SlugField(unique=True)),
                ('price_clp', models.PositiveIntegerField(default=0, verbose_name='precio (CLP)')),
                ('max_active_monitors', models.PositiveIntegerField(default=0, verbose_name='monitores activos máximos')),
                ('can_create_monitors', models.BooleanField(default=False, verbose_name='puede crear monitores')),
                ('can_run_manual_update', models.BooleanField(default=False, verbose_name='puede actualizar manualmente')),
                ('can_receive_price_alerts', models.BooleanField(default=False, verbose_name='recibe alertas de precio')),
                ('can_export', models.BooleanField(default=False, verbose_name='puede exportar')),
                ('is_pro', models.BooleanField(default=False, verbose_name='es plan pro')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['price_clp'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trialing', 'En prueba'), ('active', 'Activa'), ('past_due', 'Pago pendiente'), ('expired', 'Vencida'), ('canceled', 'Cancelada')], default='trialing', max_length=20, verbose_name='estado')),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='fin de prueba')),
                ('current_period_end', models.DateTimeField(blank=True, null=True, verbose_name='fin del período actual')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
