# Generated by Django 5.2.10 on 2026-06-20 04:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'En ejecución'), ('completed', 'Completado'), ('partial', 'Parcial'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Programado')], default='manual', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('current_step', models.CharField(blank=True, max_length=500)),
                ('progress_current', models.PositiveIntegerField(default=0)),
                ('progress_total', models.PositiveIntegerField(default=0)),
                ('monitors_processed', models.PositiveIntegerField(default=0)),
                ('products_scraped', models.PositiveIntegerField(default=0)),
                ('products_created', models.PositiveIntegerField(default=0)),
                ('products_updated', models.PositiveIntegerField(default=0)),
                ('price_changes', models.PositiveIntegerField(default=0)),
                ('error_log', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UpdateSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('interval_hours', models.PositiveIntegerField(default=6, help_text='Intervalo entre actualizaciones (1-168 horas).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)])),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Programación de actualización',
                'verbose_name_plural': 'Programación de actualización',
            },
        ),
        migrations.CreateModel(
            name='UpdateReportEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('new_product', 'Producto nuevo'), ('price_change', 'Cambio de precio')], max_length=20)),
                ('product_name', models.CharField(max_length=500)),
                ('sku_id', models.CharField(max_length=50)),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('monitor_name', models.CharField(blank=True, max_length=200)),
                ('old_price', models.PositiveIntegerField(blank=True, null=True)),
                ('new_price', models.PositiveIntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='monitoring.updatereport')),
            ],
            options={
                'ordering': ['entry_type', 'product_name'],
            },
        ),
    ]
