# Generated by Django 5.2.10 on 2026-06-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_updatereport_updateschedule_updatereportentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatereportentry',
            name='discount_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='updatereportentry',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
