# Generated by Django 5.2.10 on 2026-06-20 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50)),
                ('sku_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('seller', models.CharField(blank=True, max_length=200)),
                ('product_url', models.URLField(max_length=1000)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('reviews', models.PositiveIntegerField(default=0)),
                ('price_cmr', models.PositiveIntegerField(blank=True, null=True)),
                ('price_event', models.PositiveIntegerField(blank=True, null=True)),
                ('price_normal', models.PositiveIntegerField(blank=True, null=True)),
                ('source', models.CharField(default='falabella', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'price histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
